2024-07-11 14:25:45,693 - har_file - DEBUG - har_file.py:241 - getArkoseAndAccessToken() が呼び出されました
2024-07-11 14:25:45,693 - har_file - DEBUG - har_file.py:245 - accessToken が None です。 readHAR() を呼び出します
2024-07-11 14:25:45,694 - har_file - DEBUG - har_file.py:61 - readHAR() が呼び出されました
2024-07-11 14:25:45,696 - har_file - DEBUG - har_file.py:68 - 処理する .har ファイル: ./har\chatgpt.com.har
2024-07-11 14:25:45,870 - har_file - ERROR - har_file.py:86 - accessToken が .har ファイル内に見つかりません
2024-07-11 14:29:05,831 - har_file - DEBUG - har_file.py:243 - getArkoseAndAccessToken() が呼び出されました
2024-07-11 14:29:05,833 - har_file - DEBUG - har_file.py:247 - accessToken が None です。 readHAR() を呼び出します
2024-07-11 14:29:05,834 - har_file - DEBUG - har_file.py:61 - readHAR() が呼び出されました
2024-07-11 14:29:05,835 - har_file - DEBUG - har_file.py:68 - 処理する .har ファイル: ./har\chatgpt.com.har
2024-07-11 14:29:06,057 - har_file - DEBUG - har_file.py:132 - Start Auth Info
2024-07-11 14:29:06,059 - har_file - ERROR - har_file.py:86 - accessToken が .har ファイル内に見つかりません
2024-07-11 14:33:23,683 - har_file - DEBUG - har_file.py:242 - getArkoseAndAccessToken() が呼び出されました
2024-07-11 14:33:23,685 - har_file - DEBUG - har_file.py:246 - accessToken が None です。 readHAR() を呼び出します
2024-07-11 14:33:23,686 - har_file - DEBUG - har_file.py:61 - readHAR() が呼び出されました
2024-07-11 14:33:23,687 - har_file - DEBUG - har_file.py:68 - 処理する .har ファイル: ./har\chatgpt.com.har
2024-07-11 14:33:23,893 - har_file - ERROR - har_file.py:86 - accessToken が .har ファイル内に見つかりません
2024-07-11 14:35:22,315 - har_file - DEBUG - har_file.py:258 - getArkoseAndAccessToken() が呼び出されました
2024-07-11 14:35:22,316 - har_file - DEBUG - har_file.py:262 - accessToken が None です。 readHAR() を呼び出します
2024-07-11 14:35:22,317 - har_file - DEBUG - har_file.py:61 - readHAR() が呼び出されました
2024-07-11 14:35:22,318 - har_file - DEBUG - har_file.py:68 - 処理する .har ファイル: ./har\chatgpt.com.har
2024-07-11 14:35:22,515 - har_file - DEBUG - har_file.py:157 - JavaScript から accessToken を取得しました: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJzZXNzaW9uX2lkIjoiV2EtT3BaQ2lIR0dodE4xd2Z4MFo4eE4tNGR4UnRmMnAiLCJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJpc3NlaWRhc0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sImh0dHBzOi8vYXBpLm9wZW5haS5jb20vYXV0aCI6eyJwb2lkIjoib3JnLXRtc25NcGluanFscmViUE9URVRSTXBHbSIsInVzZXJfaWQiOiJ1c2VyLURsM0x5TWgxb21LWUplUWFtcmJaOWJiSSJ9LCJpc3MiOiJodHRwczovL2F1dGgwLm9wZW5haS5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMDkwOTk5NjM2OTk0MjMyOTg5OTQiLCJhdWQiOlsiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MSIsImh0dHBzOi8vb3BlbmFpLm9wZW5haS5hdXRoMGFwcC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzE5ODgzOTYwLCJleHAiOjE3MjA3NDc5NjAsInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUgbW9kZWwucmVhZCBtb2RlbC5yZXF1ZXN0IG9yZ2FuaXphdGlvbi5yZWFkIG9yZ2FuaXphdGlvbi53cml0ZSBvZmZsaW5lX2FjY2VzcyIsImF6cCI6IlRkSkljYmUxNldvVEh0Tjk1bnl5d2g1RTR5T282SXRHIn0.AN_K6rIrcBih-U-Rw6P7m8Ml0Zx7BJrLV-9kB5RTNxzvEi-7kMNHQUcsNvVRopTZuNUCUDpfWfiTL_nn2i9ibVp285mtHEtsNUK3OjxIZmr0VvGFv0eQczYeWwcqCsNNmplwJKXdMKj8LHzMPh7-_RuftZe89Nf98QwYm-G1fv_J22BucWy1Nxa6f37I3RzUqWj-_zDpwHI7_paa8mJgqzv9yFFYNu6mtrgOJeaQfHcUskIqBAYyIgysvH-TqJ7VVgN7k2kvxVtkw_ZIjyQNiFOMo3t3I_1qe15Rjuh750-Mo60NQDzVKolEpSRn70S6Pd0NarElMCaZS-Ig-P08GQ
2024-07-11 14:35:22,519 - har_file - DEBUG - har_file.py:213 - get_headers() が呼び出されました
2024-07-11 14:37:24,139 - har_file - DEBUG - har_file.py:258 - getArkoseAndAccessToken() が呼び出されました
2024-07-11 14:37:24,141 - har_file - DEBUG - har_file.py:262 - accessToken が None です。 readHAR() を呼び出します
2024-07-11 14:37:24,141 - har_file - DEBUG - har_file.py:61 - readHAR() が呼び出されました
2024-07-11 14:37:24,143 - har_file - DEBUG - har_file.py:68 - 処理する .har ファイル: ./har\chatgpt.com.har
2024-07-11 14:37:24,289 - har_file - DEBUG - har_file.py:157 - JavaScript から accessToken を取得しました: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJzZXNzaW9uX2lkIjoiV2EtT3BaQ2lIR0dodE4xd2Z4MFo4eE4tNGR4UnRmMnAiLCJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJpc3NlaWRhc0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sImh0dHBzOi8vYXBpLm9wZW5haS5jb20vYXV0aCI6eyJwb2lkIjoib3JnLXRtc25NcGluanFscmViUE9URVRSTXBHbSIsInVzZXJfaWQiOiJ1c2VyLURsM0x5TWgxb21LWUplUWFtcmJaOWJiSSJ9LCJpc3MiOiJodHRwczovL2F1dGgwLm9wZW5haS5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMDkwOTk5NjM2OTk0MjMyOTg5OTQiLCJhdWQiOlsiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MSIsImh0dHBzOi8vb3BlbmFpLm9wZW5haS5hdXRoMGFwcC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzE5ODgzOTYwLCJleHAiOjE3MjA3NDc5NjAsInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUgbW9kZWwucmVhZCBtb2RlbC5yZXF1ZXN0IG9yZ2FuaXphdGlvbi5yZWFkIG9yZ2FuaXphdGlvbi53cml0ZSBvZmZsaW5lX2FjY2VzcyIsImF6cCI6IlRkSkljYmUxNldvVEh0Tjk1bnl5d2g1RTR5T282SXRHIn0.AN_K6rIrcBih-U-Rw6P7m8Ml0Zx7BJrLV-9kB5RTNxzvEi-7kMNHQUcsNvVRopTZuNUCUDpfWfiTL_nn2i9ibVp285mtHEtsNUK3OjxIZmr0VvGFv0eQczYeWwcqCsNNmplwJKXdMKj8LHzMPh7-_RuftZe89Nf98QwYm-G1fv_J22BucWy1Nxa6f37I3RzUqWj-_zDpwHI7_paa8mJgqzv9yFFYNu6mtrgOJeaQfHcUskIqBAYyIgysvH-TqJ7VVgN7k2kvxVtkw_ZIjyQNiFOMo3t3I_1qe15Rjuh750-Mo60NQDzVKolEpSRn70S6Pd0NarElMCaZS-Ig-P08GQ
2024-07-11 14:37:24,292 - har_file - DEBUG - har_file.py:213 - get_headers() が呼び出されました
2024-07-11 14:38:07,412 - har_file - DEBUG - har_file.py:258 - getArkoseAndAccessToken() が呼び出されました
2024-07-11 14:46:02,629 - har_file - DEBUG - har_file.py:265 - accessToken が None です。 readHAR() を呼び出します
2024-07-11 14:46:02,631 - har_file - DEBUG - har_file.py:61 - readHAR() が呼び出されました
2024-07-11 14:46:02,632 - har_file - DEBUG - har_file.py:68 - 処理する .har ファイル: ./har\chatgpt.com.har
2024-07-11 14:46:02,863 - har_file - DEBUG - har_file.py:157 - JavaScript から accessToken を取得しました: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJzZXNzaW9uX2lkIjoiV2EtT3BaQ2lIR0dodE4xd2Z4MFo4eE4tNGR4UnRmMnAiLCJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJpc3NlaWRhc0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sImh0dHBzOi8vYXBpLm9wZW5haS5jb20vYXV0aCI6eyJwb2lkIjoib3JnLXRtc25NcGluanFscmViUE9URVRSTXBHbSIsInVzZXJfaWQiOiJ1c2VyLURsM0x5TWgxb21LWUplUWFtcmJaOWJiSSJ9LCJpc3MiOiJodHRwczovL2F1dGgwLm9wZW5haS5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMDkwOTk5NjM2OTk0MjMyOTg5OTQiLCJhdWQiOlsiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MSIsImh0dHBzOi8vb3BlbmFpLm9wZW5haS5hdXRoMGFwcC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzE5ODgzOTYwLCJleHAiOjE3MjA3NDc5NjAsInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUgbW9kZWwucmVhZCBtb2RlbC5yZXF1ZXN0IG9yZ2FuaXphdGlvbi5yZWFkIG9yZ2FuaXphdGlvbi53cml0ZSBvZmZsaW5lX2FjY2VzcyIsImF6cCI6IlRkSkljYmUxNldvVEh0Tjk1bnl5d2g1RTR5T282SXRHIn0.AN_K6rIrcBih-U-Rw6P7m8Ml0Zx7BJrLV-9kB5RTNxzvEi-7kMNHQUcsNvVRopTZuNUCUDpfWfiTL_nn2i9ibVp285mtHEtsNUK3OjxIZmr0VvGFv0eQczYeWwcqCsNNmplwJKXdMKj8LHzMPh7-_RuftZe89Nf98QwYm-G1fv_J22BucWy1Nxa6f37I3RzUqWj-_zDpwHI7_paa8mJgqzv9yFFYNu6mtrgOJeaQfHcUskIqBAYyIgysvH-TqJ7VVgN7k2kvxVtkw_ZIjyQNiFOMo3t3I_1qe15Rjuh750-Mo60NQDzVKolEpSRn70S6Pd0NarElMCaZS-Ig-P08GQ
2024-07-11 14:46:02,867 - har_file - DEBUG - har_file.py:213 - get_headers() が呼び出されました
